[project]
name = "bash-style-guide"
version = "2025.7.15"
description = "A comprehensive style guide and documentation resource for writing robust, readable, and maintainable Bash scripts."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "zensical>=0.0.15",
]
